add_newline = false
# A minimal left prompt
format = "$directory$git_branch$git_status$character"
palette = "catppuccin_frappe"
# move the rest of the prompt to the right
right_format = "$all"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_status]
disabled = false
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
stashed = '\$${count}'
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[git_metrics]
disabled = true

[terraform]
disabled = false
format = '[ $version $workspace]($style) '

[git_branch]
disabled = false
truncation_length = 20

# Enable the aws module to show the current AWS profile
[aws]
disabled = true

[status]
disabled = false
success_symbol = "🟢"
symbol = "🔴"

# Enable the kubernetes module to show the current Kubernetes context
[kubernetes]
symbol = "☸ "
disabled = false

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

