-- local Plugin = {'goolord/alpha-nvim'}
-- 
-- Plugin.name = 'alpha'
-- 
-- -- Set header
-- local config = function()
--  local alpha = require'alpha'
-- 	local dashboard = require'alpha.themes.dashboard'
--   dashboard.config.opts.noautocmd = true
-- 	dashboard.section.header.val = {
-- 			"                                                     ",
-- 			"  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ",
-- 			"  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║ ",
-- 			"  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║ ",
-- 			"  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ",
-- 			"  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ",
-- 			"  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ",
-- 			"                                                     ",
-- 	}
--   dashboard.section.buttons.val = {
--     dashboard.button( "e", "  New file" , ":ene <BAR> startinsert <CR>"),
--     dashboard.button( "q", "  Quit NVIM" , ":qa<CR>"),
--   }
--   alpha.setup(dashboard.config)
-- end
-- 
-- local layout = {}
-- 
-- Plugin.opts = {
-- 	layout = layout,
-- 	opts = {
-- 		setup = config
-- 	}
-- }
-- 
-- return Plugin
return {}
